List schema query change
datajoint/DJ-GUI-API pull request #64
Opened 2021-02-12 19:58 UTC by Synicix

2021-02-12 20:07 UTC, guzman-raphael commented
Depends on #63

2021-02-13 00:22 UTC, guzman-raphael approved these changes

2021-02-13 00:24 UTC, guzman-raphael requested changes

2021-02-13 00:24 UTC, guzman-raphael commented on dj_gui_api_server/DJConnector.py
> +        WHERE SCHEMA_NAME != "information_schema" OR "sys"
```suggestion
        WHERE SCHEMA_NAME NOT IN ("information_schema", "sys")
```

2021-02-13 01:03 UTC, Synicix commented on dj_gui_api_server/DJConnector.py
> +        WHERE SCHEMA_NAME != "information_schema" OR "sys"
Cool soudns good

2021-02-13 01:30 UTC, guzman-raphael approved these changes

2021-02-13 01:30 UTC, merged